In [2]:
import pandas as pd
import numpy as np 

import seaborn as sns 
import matplotlib.pylab as plt
%matplotlib inline

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

In [3]:
data = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML240EN-SkillsNetwork/labs/encoded_car_data.csv')
data.head()

,diesel,gas,std,turbo,convertible,hardtop,hatchback,sedan,wagon,4wd,...,wheelbase,curbweight,enginesize,boreratio,horsepower,carlength,carwidth,citympg,highwaympg,price
0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,88.6,2548.0,130.0,3.47,111.0,168.8,64.1,21.0,27.0,13495.0
1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,88.6,2548.0,130.0,3.47,111.0,168.8,64.1,21.0,27.0,16500.0
2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,94.5,2823.0,152.0,2.68,154.0,171.2,65.5,19.0,26.0,16500.0
3,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,99.8,2337.0,109.0,3.19,102.0,176.6,66.2,24.0,30.0,13950.0
4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,99.4,2824.0,136.0,3.19,115.0,176.6,66.4,18.0,22.0,17450.0

In [4]:
y = data['price'].copy()
X = data.drop(columns=['price'])

In [9]:
kf = KFold(n_splits = 3, shuffle=True)

In [10]:
for k, (train_idx, test_idx) in enumerate(kf.split(X, y)):
    print(k)
    print("TRAIN: ", train_idx)
    print("TEST: ", test_idx)

0
TRAIN:  [  0   1   2   3   4   5   7   8   9  10  11  12  15  16  17  19  20  21
  22  24  25  26  27  28  29  30  31  32  33  34  36  38  39  41  44  46
  47  48  49  50  52  53  54  56  57  59  60  67  69  70  72  73  74  75
  76  78  79  80  81  85  86  87  89  91  92  96  98 100 101 102 103 104
 106 107 108 109 110 111 112 115 116 118 121 124 125 128 129 130 131 133
 134 135 136 138 142 144 148 149 150 152 153 154 155 156 158 159 160 161
 163 164 167 168 169 170 172 175 177 180 181 182 183 184 185 187 188 189
 190 192 193 194 195 196 197 198 200 204]
TEST:  [  6  13  14  18  23  35  37  40  42  43  45  51  55  58  61  62  63  64
  65  66  68  71  77  82  83  84  88  90  93  94  95  97  99 105 113 114
 117 119 120 122 123 126 127 132 137 139 140 141 143 145 146 147 151 157
 162 165 166 171 173 174 176 178 179 186 191 199 201 202 203]
1
TRAIN:  [  0   2   3   4   5   6   8  10  13  14  15  16  18  19  23  24  27  31
  32  33  34  35  37  38  39  40  41  42  43  45  48  49  50  51  55  56
  58  61  62  63  64  65  66  67  68  70  71  73  76  77  81  82  83  84
  87  88  90  92  93  94  95  97  99 100 101 103 104 105 106 107 108 109
 112 113 114 116 117 119 120 122 123 125 126 127 128 129 130 132 133 135
 136 137 138 139 140 141 143 144 145 146 147 148 151 153 156 157 160 162
 163 164 165 166 169 171 172 173 174 175 176 177 178 179 180 184 185 186
 187 191 194 195 198 199 200 201 202 203 204]
TEST:  [  1   7   9  11  12  17  20  21  22  25  26  28  29  30  36  44  46  47
  52  53  54  57  59  60  69  72  74  75  78  79  80  85  86  89  91  96
  98 102 110 111 115 118 121 124 131 134 142 149 150 152 154 155 158 159
 161 167 168 170 181 182 183 188 189 190 192 193 196 197]
2
TRAIN:  [  1   6   7   9  11  12  13  14  17  18  20  21  22  23  25  26  28  29
  30  35  36  37  40  42  43  44  45  46  47  51  52  53  54  55  57  58
  59  60  61  62  63  64  65  66  68  69  71  72  74  75  77  78  79  80
  82  83  84  85  86  88  89  90  91  93  94  95  96  97  98  99 102 105
 110 111 113 114 115 117 118 119 120 121 122 123 124 126 127 131 132 134
 137 139 140 141 142 143 145 146 147 149 150 151 152 154 155 157 158 159
 161 162 165 166 167 168 170 171 173 174 176 178 179 181 182 183 186 188
 189 190 191 192 193 196 197 199 201 202 203]
TEST:  [  0   2   3   4   5   8  10  15  16  19  24  27  31  32  33  34  38  39
  41  48  49  50  56  67  70  73  76  81  87  92 100 101 103 104 106 107
 108 109 112 116 125 128 129 130 133 135 136 138 144 148 153 156 160 163
 164 169 172 175 177 180 184 185 187 194 195 198 200 204]